version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - frontend

networks:
  frontend:  
    driver: bridge
  backend:
    driver: bridge
